import os
import sys
import time
import shutil
import logging
import platform
import zipfile
import threading
import subprocess
import urllib.request
import httpx
import requests

logger = logging.getLogger("go2rtc_manager")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s")

GO2RTC_API_URL = "http://127.0.0.1:1984"
GO2RTC_VERSION = "v1.9.8"


class Go2rtcManager:
    """
    Manages the lifecycle of go2rtc binary, generates go2rtc.yaml configuration,
    and acts as a proxy for WebRTC, MSE (MP4), and snapshot streams.
    """

    def __init__(self):
        self.process = None
        self.log_thread = None
        self.dir_path = os.path.dirname(os.path.abspath(__file__))
        self.config_path = os.path.join(self.dir_path, "go2rtc.yaml")
        self.host = os.getenv("CAMERA_HOST", "10.10.1.17")
        self.port = int(os.getenv("RTSP_PORT", 554))
        self.path = os.getenv("RTSP_PATH", "/stream1")
        if not self.path.startswith("/"):
            self.path = "/" + self.path

        self.user = os.getenv("CAMERA_USER", "NMSIOTYOGYA1")
        self.password = os.getenv("CAMERA_PASS", "Nayaka2025")
        self.rtsp_url_override = os.getenv("RTSP_URL")
        self.public_ip = os.getenv("WEBRTC_PUBLIC_IP", "110.232.92.134")

    def get_rtsp_url(self, mask_password=False):
        if self.rtsp_url_override:
            url = self.rtsp_url_override
            if mask_password and "@" in url:
                parts = url.split("@")
                proto_user = parts[0].split(":")
                return f"{proto_user[0]}:***@{parts[1]}"
            return url

        if self.user and self.password:
            pwd = "****" if mask_password else self.password
            return f"rtsp://{self.user}:{pwd}@{self.host}:{self.port}{self.path}"
        return f"rtsp://{self.host}:{self.port}{self.path}"

    def _ensure_binary(self) -> str:
        """
        Locates the go2rtc executable or downloads it automatically if missing.
        """
        system = platform.system().lower()
        machine = platform.machine().lower()

        # Check in PATH
        found = shutil.which("go2rtc")
        if found:
            return found

        # Check standard Linux path
        if os.path.exists("/usr/local/bin/go2rtc"):
            return "/usr/local/bin/go2rtc"

        # Check local directory
        local_exe = os.path.join(self.dir_path, "go2rtc.exe" if system == "windows" else "go2rtc")
        if os.path.exists(local_exe):
            return local_exe

        # Attempt auto-download
        logger.info(f"go2rtc binary not found. Attempting automatic download for {system} ({machine})...")
        try:
            if system == "windows":
                url = f"https://github.com/AlexxIT/go2rtc/releases/download/{GO2RTC_VERSION}/go2rtc_win64.zip"
                zip_path = os.path.join(self.dir_path, "go2rtc_temp.zip")
                urllib.request.urlretrieve(url, zip_path)
                with zipfile.ZipFile(zip_path, "r") as zip_ref:
                    zip_ref.extractall(self.dir_path)
                if os.path.exists(zip_path):
                    os.remove(zip_path)
                if os.path.exists(local_exe):
                    logger.info(f"Downloaded go2rtc to {local_exe}")
                    return local_exe
            else:
                arch = "arm64" if "aarch" in machine or "arm" in machine else "amd64"
                url = f"https://github.com/AlexxIT/go2rtc/releases/download/{GO2RTC_VERSION}/go2rtc_linux_{arch}"
                urllib.request.urlretrieve(url, local_exe)
                os.chmod(local_exe, 0o755)
                logger.info(f"Downloaded go2rtc to {local_exe}")
                return local_exe
        except Exception as e:
            logger.warning(f"Could not auto-download go2rtc: {e}")

        return local_exe

    def generate_config(self):
        rtsp_url = self.get_rtsp_url(mask_password=False)
        config_content = f"""# Auto-generated by Worker_CCTV
streams:
  cctv:
    - {rtsp_url}#backchannel=0

api:
  listen: ":1984"

webrtc:
  listen: ":8555"
  candidates:
    - {self.public_ip}:8555
    - stun:8555

log:
  level: "info"
"""
        with open(self.config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        logger.info(f"go2rtc.yaml configured for stream: {self.get_rtsp_url(mask_password=True)}")

    def _pipe_reader(self, pipe):
        """
        Reads lines from go2rtc stdout pipe to prevent OS buffer deadlocks.
        """
        try:
            for line in iter(pipe.readline, ""):
                if not line:
                    break
                logger.info(f"[go2rtc] {line.strip()}")
        except Exception:
            pass
        finally:
            try:
                pipe.close()
            except Exception:
                pass

    def start(self):
        self.generate_config()
        executable = self._ensure_binary()

        if not os.path.exists(executable) and not shutil.which(executable):
            logger.warning(
                f"go2rtc binary not found at '{executable}'. If running locally, please install go2rtc."
            )
            return False

        try:
            logger.info(f"Launching go2rtc from {executable} with config {self.config_path}...")
            self.process = subprocess.Popen(
                [executable, "-c", self.config_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
            )

            # Start thread to continuously read output and prevent deadlocks
            self.log_thread = threading.Thread(
                target=self._pipe_reader, args=(self.process.stdout,), daemon=True
            )
            self.log_thread.start()

            time.sleep(1.0)

            # Verify it did not crash immediately
            poll = self.process.poll()
            if poll is not None:
                logger.error(f"go2rtc process terminated immediately with exit code {poll}")
                return False

            logger.info("go2rtc streaming daemon is running and listening on :1984 & :8555!")
            return True
        except Exception as e:
            logger.error(f"Failed to start go2rtc: {e}")
            return False

    def stop(self):
        if self.process:
            logger.info("Terminating go2rtc daemon...")
            self.process.terminate()
            try:
                self.process.wait(timeout=3.0)
            except subprocess.TimeoutExpired:
                self.process.kill()
            self.process = None

    def is_alive(self):
        if self.process and self.process.poll() is None:
            return True
        return False

    def get_streams_status(self):
        try:
            res = requests.get(f"{GO2RTC_API_URL}/api/streams", timeout=2.0)
            if res.status_code == 200:
                data = res.json()
                cctv = data.get("cctv", {})
                producers = cctv.get("producers", [])
                consumers = cctv.get("consumers", [])

                codecs = []
                for p in producers:
                    medias = p.get("medias", [])
                    for m in medias:
                        if "video" in str(m).lower():
                            codecs.append(str(m))

                return {
                    "engine": "go2rtc",
                    "status": "online" if producers else "waiting_stream",
                    "producers_count": len(producers),
                    "consumers_count": len(consumers),
                    "video_tracks": codecs,
                    "latency": "< 0.5s (Real-Time WebRTC / MSE)",
                    "rtsp_target": self.get_rtsp_url(mask_password=True),
                }
        except Exception as e:
            return {
                "engine": "go2rtc",
                "status": "offline",
                "error": str(e),
                "rtsp_target": self.get_rtsp_url(mask_password=True),
            }

    async def proxy_webrtc_offer(self, sdp_offer: str) -> str:
        """
        Forwards WebRTC SDP Offer to go2rtc API and returns SDP Answer.
        """
        try:
            async with httpx.AsyncClient(timeout=6.0) as client:
                resp = await client.post(
                    f"{GO2RTC_API_URL}/api/webrtc?src=cctv",
                    content=sdp_offer,
                    headers={"Content-Type": "application/sdp"},
                )
                resp.raise_for_status()
                return resp.text
        except Exception as e:
            logger.error(f"go2rtc WebRTC proxy error: {e}")
            raise e

    async def proxy_snapshot(self):
        """
        Fetches instant high-res JPEG keyframe from go2rtc without throwing exceptions.
        """
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                resp = await client.get(f"{GO2RTC_API_URL}/api/frame.jpeg?src=cctv")
                if resp.status_code == 200 and len(resp.content) > 100:
                    return resp.content, resp.headers.get("content-type", "image/jpeg")
        except Exception as e:
            logger.debug(f"go2rtc frame.jpeg not ready: {e}")
        return None, "image/jpeg"
