import os
import sys
import time
import shutil
import logging
import subprocess
import httpx
import requests

logger = logging.getLogger("go2rtc_manager")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s")

GO2RTC_API_URL = "http://127.0.0.1:1984"


class Go2rtcManager:
    """
    Manages the lifecycle of go2rtc binary, generates go2rtc.yaml configuration,
    and acts as a proxy for WebRTC, MSE (MP4), and snapshot streams.
    """

    def __init__(self):
        self.process = None
        self.config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "go2rtc.yaml")
        self.host = os.getenv("CAMERA_HOST", "10.10.1.17")
        self.port = int(os.getenv("RTSP_PORT", 554))
        self.path = os.getenv("RTSP_PATH", "/stream1")
        if not self.path.startswith("/"):
            self.path = "/" + self.path

        self.user = os.getenv("CAMERA_USER", "NMSIOTYOGYA1")
        self.password = os.getenv("CAMERA_PASS", "Nayaka2025")
        self.rtsp_url_override = os.getenv("RTSP_URL")

    def get_rtsp_url(self, mask_password=False):
        if self.rtsp_url_override:
            url = self.rtsp_url_override
            if mask_password and "@" in url:
                parts = url.split("@")
                proto_user = parts[0].split(":")
                return f"{proto_user[0]}:***@{parts[1]}"
            return url

        if self.user and self.password:
            pwd = "****" if mask_password else self.password
            return f"rtsp://{self.user}:{pwd}@{self.host}:{self.port}{self.path}"
        return f"rtsp://{self.host}:{self.port}{self.path}"

    def generate_config(self):
        rtsp_url = self.get_rtsp_url(mask_password=False)
        # go2rtc config
        config_content = f"""# Auto-generated by Worker_CCTV
streams:
  cctv:
    - {rtsp_url}#backchannel=0

api:
  listen: "127.0.0.1:1984"

webrtc:
  listen: ":8555"

log:
  level: "info"
"""
        with open(self.config_path, "w", encoding="utf-8") as f:
            f.write(config_content)
        logger.info(f"go2rtc.yaml configured for stream: {self.get_rtsp_url(mask_password=True)}")

    def start(self):
        self.generate_config()

        # Find go2rtc executable
        executable = shutil.which("go2rtc") or "/usr/local/bin/go2rtc"
        if not os.path.exists(executable) and not shutil.which("go2rtc"):
            logger.warning(
                f"go2rtc binary not found at {executable}. If running locally, install go2rtc or run inside Docker."
            )
            return False

        try:
            logger.info(f"Launching go2rtc from {executable} with config {self.config_path}...")
            self.process = subprocess.Popen(
                [executable, "-config", self.config_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            time.sleep(1.0)
            logger.info("go2rtc streaming daemon started successfully!")
            return True
        except Exception as e:
            logger.error(f"Failed to start go2rtc: {e}")
            return False

    def stop(self):
        if self.process:
            logger.info("Terminating go2rtc daemon...")
            self.process.terminate()
            try:
                self.process.wait(timeout=3.0)
            except subprocess.TimeoutExpired:
                self.process.kill()
            self.process = None

    def is_alive(self):
        if self.process and self.process.poll() is None:
            return True
        return False

    def get_streams_status(self):
        try:
            res = requests.get(f"{GO2RTC_API_URL}/api/streams", timeout=2.0)
            if res.status_code == 200:
                data = res.json()
                cctv = data.get("cctv", {})
                producers = cctv.get("producers", [])
                consumers = cctv.get("consumers", [])
                
                # Check video track details
                codecs = []
                for p in producers:
                    medias = p.get("medias", [])
                    for m in medias:
                        if "video" in str(m).lower():
                            codecs.append(str(m))

                return {
                    "engine": "go2rtc",
                    "status": "online" if producers else "waiting_stream",
                    "producers_count": len(producers),
                    "consumers_count": len(consumers),
                    "video_tracks": codecs,
                    "latency": "< 0.5s (Real-Time WebRTC / MSE)",
                    "rtsp_target": self.get_rtsp_url(mask_password=True),
                }
        except Exception as e:
            return {
                "engine": "go2rtc",
                "status": "offline",
                "error": str(e),
                "rtsp_target": self.get_rtsp_url(mask_password=True),
            }

    async def proxy_webrtc_offer(self, sdp_offer: str) -> str:
        """
        Forwards WebRTC SDP Offer to go2rtc API and returns SDP Answer.
        """
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.post(
                f"{GO2RTC_API_URL}/api/webrtc?src=cctv",
                content=sdp_offer,
                headers={"Content-Type": "application/sdp"},
            )
            resp.raise_for_status()
            return resp.text

    async def proxy_snapshot(self):
        """
        Fetches instant high-res JPEG keyframe from go2rtc.
        """
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(f"{GO2RTC_API_URL}/api/frame.jpeg?src=cctv")
            if resp.status_code == 200:
                return resp.content, resp.headers.get("content-type", "image/jpeg")
        return None, "image/jpeg"
