"""
Django settings for django_mqtt project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import paho.mqtt.client as mqtt
from django.conf import settings
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uv@(()w_3ngn$lu_2jspyy7mbp)+x4dk!760o5a^a7wt4z8&@('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

allowed_hosts_env = os.environ.get("ALLOWED_HOSTS")
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",")]
else:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "110.232.92.134",
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'speakerapp',
    'corsheaders',
    'rest_framework',
    'devicestatusapp',
    # 'gps_tracer',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True

# TRACCAR_BASE_URL = "http://demo.traccar.org:8082"
# TRACCAR_USER = "testinggps"
# TRACCAR_PASS = "Nayaka2025"

ROOT_URLCONF = 'django_mqtt.urls'

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # DEV

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000","http://103.176.45.14",
]
CORS_ALLOW_CREDENTIALS = True



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_mqtt.wsgi.application'


# MQTT Settings
MQTT_SERVER = os.environ.get("MQTT_SERVER", "emqx.nayakanms.com")
MQTT_PORT = int(os.environ.get("MQTT_PORT", 1884))
MQTT_USER = os.environ.get("MQTT_USER", "nyk_ws")
MQTT_PASSWORD = os.environ.get("MQTT_PASSWORD", "ws")
MQTT_TOPIC_SUB = os.environ.get("MQTT_TOPIC_SUB", "nms/E32_WB_WS/whitebox/config")
MQTT_TOPIC_PUB = os.environ.get("MQTT_TOPIC_PUB", "/matalite-test/reply/")
MQTT_TOPIC_PUB2 = os.environ.get("MQTT_TOPIC_PUB2", "nms/E32_WB_WS/whitebox/#")
MQTT_TOPIC_SPEAKER_CONFIG = os.environ.get("MQTT_TOPIC_SPEAKER_CONFIG", "nms/esp32-speaker-003734fe8ce0/speaker/config")

# New MQTT Settings (for Lamp/Relay) - Unified with primary settings
NEW_MQTT_SERVER = MQTT_SERVER
NEW_MQTT_PORT = MQTT_PORT
NEW_MQTT_USER = MQTT_USER
NEW_MQTT_PASSWORD = MQTT_PASSWORD
NEW_MQTT_TOPIC_SUB = MQTT_TOPIC_SUB


# client = mqtt.Client()
# client.username_pw_set(settings.MQTT_USER, settings.MQTT_PASSWORD)
# client.connect(
#     host=settings.MQTT_SERVER,
#     port=settings.MQTT_PORT,
#     keepalive=settings.MQTT_KEEPALIVE
# )


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/django/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
