# Generated by Django 5.2.8 on 2026-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_site_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='E32_WS (Sector A)', max_length=50)),
                ('temperature', models.FloatField(default=32.04, help_text='Suhu dalam °C')),
                ('humidity', models.FloatField(default=45.66, help_text='Kelembapan dalam %RH')),
                ('pressure', models.FloatField(default=100.67, help_text='Tekanan dalam kPa')),
                ('wind_speed', models.FloatField(default=0.89, help_text='Kecepatan Angin dalam m/s')),
                ('wind_direction', models.FloatField(default=324.0, help_text='Arah Angin dalam derajat')),
                ('rain', models.FloatField(default=27.4, help_text='Curah Hujan dalam mm')),
                ('light', models.FloatField(default=5817.0, help_text='Cahaya dalam lux')),
                ('radiation', models.FloatField(default=45.0, help_text='Radiasi dalam W/m2')),
                ('pm25', models.FloatField(default=1.0, help_text='PM2.5 dalam ug/m3')),
                ('pm10', models.FloatField(default=2.0, help_text='PM10 dalam ug/m3')),
                ('negative_ion', models.FloatField(default=138.0, help_text='Ion Negatif dalam ion/cm3')),
                ('noise', models.FloatField(default=0.0, help_text='Kebisingan dalam dB')),
                ('co', models.FloatField(blank=True, default=None, null=True)),
                ('co2', models.FloatField(blank=True, default=None, null=True)),
                ('no2', models.FloatField(blank=True, default=None, null=True)),
                ('so2', models.FloatField(blank=True, default=None, null=True)),
                ('aqi', models.IntegerField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
