# Generated by Django 5.2.8 on 2026-08-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLEScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('mac', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('namespace_id', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'BLE Scan',
                'verbose_name_plural': 'BLE Scans',
                'ordering': ['-timestamp'],
            },
        ),
    ]
