# Generated by Django 5.2.8 on 2026-08-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_blescan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLEDevice',
            fields=[
                ('mac', models.CharField(help_text='MAC Address BLE Beacon', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Nama unik perangkat (contoh: BTSID TII)', max_length=100)),
                ('location', models.CharField(default='Sector A - Upper Level', help_text='Deskripsi lokasi pemasangan', max_length=100)),
                ('installation_date', models.DateField(blank=True, help_text='Tanggal pemasangan perangkat', null=True)),
                ('vendor', models.CharField(default='Huawei', help_text='Vendor perangkat', max_length=50)),
                ('height', models.CharField(default='38 Meter', help_text='Tinggi pemasangan di tower', max_length=50)),
                ('rssi_threshold', models.IntegerField(default=-75, help_text='Ambang batas RSSI untuk deteksi pencurian (default: -75 dBm)')),
                ('image', models.FileField(blank=True, help_text='Gambar/Foto Antena', null=True, upload_to='ble_devices/')),
                ('is_active', models.BooleanField(default=True, help_text='Status pemantauan aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BLE Device Config',
                'verbose_name_plural': 'BLE Device Configs',
                'ordering': ['name'],
            },
        ),
    ]
