# Generated by Django 5.2.8 on 2026-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_bledevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp of scan log')),
                ('reader_id', models.CharField(db_index=True, help_text='ID of the RFID reader', max_length=100)),
                ('tag_epc', models.CharField(db_index=True, help_text='EPC ID of the RFID tag scanned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RFID Scan',
                'verbose_name_plural': 'RFID Scans',
                'ordering': ['-timestamp'],
            },
        ),
    ]
