# Generated by Django 5.2.8 on 2026-08-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_rfidscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredRFIDReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(db_index=True, help_text='ID of the registered RFID reader', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Custom name/label for the reader', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registered RFID Reader',
                'verbose_name_plural': 'Registered RFID Readers',
                'ordering': ['reader_id'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredRFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_epc', models.CharField(db_index=True, help_text='EPC ID of the registered RFID tag', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Custom name/label for the tag', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registered RFID Tag',
                'verbose_name_plural': 'Registered RFID Tags',
                'ordering': ['tag_epc'],
            },
        ),
    ]
