# Generated by Django 5.2.8 on 2026-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_registeredrfidreader_registeredrfidtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableHealthTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, default='Cable_Sense_01', help_text='ID perangkat sensor kabel', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu data diterima')),
                ('vibration', models.FloatField(default=0.0, help_text='Getaran kabel (vibration) dalam m/s² atau g')),
                ('tension', models.FloatField(default=100.0, help_text='Tegangan tarik kabel (tension) dalam % atau kg')),
                ('impact', models.FloatField(default=0.0, help_text='Benturan mekanis (impact) dalam g')),
                ('is_cut', models.BooleanField(default=False, help_text='Indikator aktivitas pencurian (kabel dipotong/dilepas)')),
                ('temperature', models.FloatField(default=25.0, help_text='Suhu kabel/lingkungan dalam °C')),
                ('device_status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Offline', 'Offline')], default='Normal', help_text='Kondisi kesehatan/status perangkat', max_length=20)),
                ('signal_strength', models.IntegerField(default=-60, help_text='Kekuatan sinyal RSSI dalam dBm')),
                ('is_connected', models.BooleanField(default=True, help_text='Status konektivitas perangkat ke gateway')),
            ],
            options={
                'verbose_name': 'Cable Health Telemetry',
                'verbose_name_plural': 'Cable Health Telemetry Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device_id', '-timestamp'], name='monitoring__device__ed1038_idx')],
            },
        ),
    ]
