# Generated by Django 5.2.8 on 2026-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestatusapp', '0002_doorstatuslog_alter_devicestate_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('camera_name', models.CharField(max_length=100)),
                ('rtsp_url', models.CharField(max_length=500)),
                ('onvif_url', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(default=1920)),
                ('height', models.IntegerField(default=1080)),
                ('is_active', models.BooleanField(default=True)),
                ('detection_zones', models.TextField(default='[]')),
            ],
        ),
    ]
