# Generated by Django 5.2.8 on 2026-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestatusapp', '0003_cctvcamera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvcamera',
            name='afternoon_end',
            field=models.IntegerField(default=18, help_text='Jam selesai baseline siang (0-23)'),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='afternoon_start',
            field=models.IntegerField(default=12, help_text='Jam mulai baseline siang (0-23)'),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='morning_end',
            field=models.IntegerField(default=12, help_text='Jam selesai baseline pagi (0-23)'),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='morning_start',
            field=models.IntegerField(default=6, help_text='Jam mulai baseline pagi (0-23)'),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='night_end',
            field=models.IntegerField(default=6, help_text='Jam selesai baseline malam (0-23)'),
        ),
        migrations.AddField(
            model_name='cctvcamera',
            name='night_start',
            field=models.IntegerField(default=18, help_text='Jam mulai baseline malam (0-23)'),
        ),
    ]
