# Generated by Django 5.2.8 on 2026-09-14 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicestatusapp', '0004_cctvcamera_afternoon_end_cctvcamera_afternoon_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
